version: '3'
    
services:
    db:
      image: kartoza/postgis
      environment:
        - POSTGRES_DB=exevada
        - POSTGRES_USER=c3s62admin
        - POSTGRES_PASSWORD=c3s62psswd
    web:
      build: .
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/opt/exevada
      ports:
        - "8000:8000"
      depends_on:
        - db