version: '3'
    
services:
    db:
      image: kartoza/postgis
      hostname: db
      environment:
        - POSTGRES_DB=exevada_prod
        - POSTGRES_USER=exevada_user
        - POSTGRES_PASSWORD=exevada_password
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
    web:
      build: .
      command: runserver 0.0.0.0:8000
      environment:
        - DEBUG=1
        - DEPLOY=0
        - SECRET_KEY=foo
        - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 0.0.0.0 [::1]
        - DJANGO_DB=exevada_prod
        - DJANGO_USER=exevada_user
        - DJANGO_PASSWORD=exevada_password
        - DJANGO_HOST=db
        - DJANGO_PORT=5432
        - DATABASE=postgres
      ports:
        - "8000:8000"
      depends_on:
        - db

volumes:
  postgres_data: