version: '3'
    
services:
    db:
      image: kartoza/postgis
      hostname: db
      environment:
        - POSTGRES_DB=exevada
        - POSTGRES_USER=exevada_user
        - POSTGRES_PASSWORD=exevada_password
      ports:
        - 5432:5432
      volumes:
        - ./postgres-data:/var/lib/postgresql/data
    web:
      build:
        context: .
        dockerfile: Dockerfile-prod
      command: gunicorn wsgi:application --bind 0.0.0.0:8000
      volumes:
        - .:/opt/exevada
      environment:
        - DEBUG=0
        - DEPLOY=1
        - SECRET_KEY=change_me
        - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
        - DJANGO_DB=exevada
        - DJANGO_USER=exevada_user
        - DJANGO_PASSWORD=exevada_password
        - DJANGO_HOST=db
        - DJANGO_PORT=5432
        - DATABASE=postgres
      ports:
        - 8000:8000
      depends_on:
        - db
    nginx:
      build: ./nginx
      ports:
        - 1337:80
      depends_on:
        - web

volumes:
  postgres_data: