version: '3'
    
services:
    db:
      image: kartoza/postgis
      hostname: db
      environment:
        - POSTGRES_DB=exevada
        - POSTGRES_USER=dbuser
        - POSTGRES_PASSWORD=dbpsswd
      ports:
        - "5432:5432"
      volumes:
        - ./postgres-data:/var/lib/postgresql/data
    web:
      build: .
      command: /bin/bash -c "sleep 5 ; ./entrypoint.sh"
      volumes:
        - .:/opt/exevada
      ports:
        - "8000:8000"
      depends_on:
        - db
